app/subscriptions/views.py
from flask import request, redirect, url_for, render_template, Blueprint, current_app, g, flash
from flask_login import login_required, login_user, logout_user, current_user
from app import app, db, celery, mail, Message, login_manager
from app.models import Subscription, User 

subscriptions_blueprint = Blueprint('subscriptions', __name__, template_folder='templates')

@subscriptions_blueprint.route('/subscriptions')
@login_required
def subscriptions():
    subscrs = Subscription.query.filter_by(user_id=current_user.id).all()
    return render_template('subscriptions.html', subscrs = subscrs)


@subscriptions_blueprint.route('/subscriptions/new')
@login_required
def subscriptions_add():
    if current_user.subscr_left > 0:
        newsubscr = Subscription(user_id = current_user.id)
        user = User.query.filter(User.id==current_user.id).first()
        user.subscr_left = current_user.subscr_left - 1
        db.session.add(user)
        db.session.add(newsubscr)
        db.session.commit()
        flash("Subscription {sub} added, you have {numsubscr} subscriptions left".format(sub=newsubscr.id, numsubscr=user.subscr_left), 'success')
    else:
        flash("You have no subscriptions left, upgrade your plan to get more", 'warning')
    return redirect(url_for('subscriptions.subscriptions'))


@subscriptions_blueprint.route('/subscriptions/edit/<int:sub_id>', methods=['GET', 'POST'])
@login_required
def subscriptions_edit(sub_id):
    sub = Subscription.query.filter(Subscription.id == sub_id, Subscription.user_id == current_user.id).first()
    if sub is not None:
        # edit
        # add
        flash("Subscription %s edited" % sub.id, 'success')

        db.session.add(sub)
        db.session.commit()
    else:
        flash("Subscription %s not found" % sub_id, 'info')
    return redirect(url_for('subscriptions.subscriptions'))


@subscriptions_blueprint.route('/subscriptions/delete/<int:sub_id>', methods=['GET', 'POST'])
@login_required
def subscriptions_delete(sub_id):
    sub = Subscription.query.filter(Subscription.id == sub_id, Subscription.user_id == current_user.id).first()
    if sub is not None:
        flash("Subscription %s deleted" % sub.id, 'success')
        db.session.delete(sub)
        db.session.commit()
    else:
        flash("Subscription %s not found" % sub_id, 'info')

    return redirect(url_for('subscriptions.subscriptions'))

app/subscriptions/templates/index.html
{% extends 'base.html' %}
{% block content %}
subscr template
{% endblock %}

app/subscriptions/templates/subscriptions.html
{% extends 'base.html' %}
{% block content %}
{% with messages = get_flashed_messages(with_categories=True) %}
{% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}}" role="alert">
      {{ message }}
    </div>
    {% endfor %}
  {% endif %}
{% endwith %}


subscr template. 

{% if current_user.is_authenticated %}
Hi {{ current_user.login }}!
You have {{current_user.subscr_left }} subscriptions left
{% endif %}

<a href="{{url_for('subscriptions.subscriptions_add')}}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">New subscription</a>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">text</th>
      <th scope="col">query</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for subscr in subscrs %}
   
    <tr>
      <th scope="row">{{ subscr.id }}</th>
      <td>some text</td>
      <td>query</td>
      <td><a href="{{url_for('subscriptions.subscriptions_edit', sub_id=subscr.id)}}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">edit</a> <a href="{{url_for('subscriptions.subscriptions_delete', sub_id=subscr.id)}}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">delete</a></td>
    </tr>
    {% endfor %}

  </tbody>
</table>

{% endblock %}