app/main/views.py
from flask import render_template, Blueprint

mainpage_blueprint = Blueprint('main', __name__, template_folder='templates')

@mainpage_blueprint.route('/')
def index():
    return render_template('main.html')

app/users/views.py
import datetime
from flask import request, redirect, url_for, render_template, Blueprint, current_app, g, flash
from flask_login import login_required, login_user, logout_user, current_user
from app import app, db, celery, mail, Message, login_manager
from app.models import User, TariffPlan
from passlib.hash import sha512_crypt
from itsdangerous import URLSafeTimedSerializer

users_blueprint = Blueprint('users', __name__, template_folder='templates')

@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('subscriptions.subscriptions'))

    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(login = username).first()
        if not user:
            error = 'Invalid user'
            flash(error, 'warning')
        elif not user.verify_password(password):
            error = 'Wrong password'
            flash(error, 'warning')
        else:
            if user.is_confirmed and user.is_active:
                login_user(user)
                return redirect(url_for('subscriptions.subscriptions'))
            else:
                error = 'User is not confirmed, check your mail'
                flash(error, 'warning')

    return render_template('login.html')

@users_blueprint.route("/register", methods=['GET', 'POST',])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('subscriptions.subscriptions'))
    
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        if len(password) < 4:
            error = 'Password too short'
            flash(error, 'warning')
            return render_template('register.html')

        user = User.query.filter_by(login = username).first()
        if user is not None:
            error = 'Login already taken'
            flash(error, 'warning')
        else:
            try:
                freeplan = TariffPlan.query.filter(TariffPlan.price==0).first()
                user = User(login=username, plan_id = freeplan.id, subscr_left=freeplan.subscr_num)
                user.hash_password(password)
                user.registered_on = datetime.datetime.now()
                db.session.add(user)
                db.session.commit()
                token = generate_confirmation_token(user.login)
                flash('Confirmation link is sent to your email', 'info')
                # send confirmation email with celery
                send_async_email.delay([user.login,], url_for('users.activate', token=token, _external=True))
                
                return redirect(url_for('users.login'))

            except AssertionError as er:
                flash(er, 'warning')

    return render_template('register.html')


@users_blueprint.route("/confirm/<token>", methods=['GET',])
def activate(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    user = User.query.filter_by(login=email).first_or_404()
    if user.is_confirmed:
        flash('Account already confirmed. Please login.', 'success')
    else:
        user.is_confirmed = True
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('users.login'))


@users_blueprint.route("/logout")
def logout():
    if current_user.is_authenticated:
        logout_user()
        
    return redirect(url_for('users.login'))


def generate_confirmation_token(email):
    serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
    return serializer.dumps(email, salt=app.config['SECURITY_PASSWORD_SALT'])

def confirm_token(token, expiration=3600):
    serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
    try:
        email = serializer.loads(
            token,
            salt=app.config['SECURITY_PASSWORD_SALT'],
            max_age=expiration
        )
    except:
        return False

    return email

@celery.task
def send_async_email(recipients, link):
    """Background task to send an email with Flask-Mail."""
    subject = "Confirmation email for trololo.info"
    sender = 'noreply@trololo.info'
    msg = Message(subject, sender=sender, recipients=recipients)
    msg.body = 'You can activate your account here: %s' % link
    with app.app_context():
        mail.send(msg)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/templates/base.html
<!doctype html>
<html>
  <head>
    <title>PROJECT NAME</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>
    
    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
      <a class="navbar-brand" href="#">Fixed navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="{{'nav-item active' if request.path == url_for('main.index') else 'nav-item'}}">
            <a class="nav-link" href="{{url_for('main.index')}}">Home </a>
          </li>
	  {% if current_user.is_authenticated %}
          <li class="{{'nav-item active' if request.path == url_for('users.logout') else 'nav-item'}}">
            <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
          </li>
	  <li class="{{'nav-item active' if url_for('subscriptions.subscriptions') in  request.path else 'nav-item'}}">
            <a class="nav-link" href="{{url_for('subscriptions.subscriptions')}}">Subscriptions</a>
          </li>
	  {% else %}
	  <li class="{{'nav-item active' if request.path == url_for('users.login') else 'nav-item'}}">
            <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
          </li>
	  <li class="{{'nav-item active' if request.path == url_for('users.register') else 'nav-item'}}">
            <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
          </li>
	  {% endif %}
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Settings</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container"> 
      {% block content %} 
      base template [this should never be shown]
      {% endblock %}
    </main>
    <footer class="container-fluid">
      <nav class="navbar fixed-bottom">
	Footer text
      </nav>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
  </body>
</html>